baseURL = "https://www.glossary.dev"
languageCode = "en-us"
title = "Developer Glossary"
copyright = "MIT License, <a href='https://github.com/do-community/developer-glossary'>Contribute on GitHub</a>"
description = "test"

disableKinds = ["taxonomy", "term"]

[params]
  titleEmoji = ":tada:"

[Permalinks]
  term = ":slug"
